@startuml

class TcpSrvSum{
+main(args)
+run()
}

class AutomaticallyAssignOrderToFreeAGVController{
+getOrdersToAssign()
+getAGVsAvailable()
+updateOrder(order)
+updateAGV(agv)
}

class PersistenceContext{
+repositories()
}

class RepositoryFactory{
+create()
}

database OrderRepository{
}

database AGVRepository{
}

database TaskRepository{
}

class TheOrder{
+setStatus(status)
}

class AGV{
+setTaskStatus(taskStatus)
}

class TheTask{
+create()
}

TcpSrvSum --> AutomaticallyAssignOrderToFreeAGVController

AutomaticallyAssignOrderToFreeAGVController --> PersistenceContext

PersistenceContext --> RepositoryFactory

RepositoryFactory --> OrderRepository
RepositoryFactory --> AGVRepository
RepositoryFactory --> TaskRepository

AutomaticallyAssignOrderToFreeAGVController --> TheOrder
AutomaticallyAssignOrderToFreeAGVController --> AGV
AutomaticallyAssignOrderToFreeAGVController --> TheTask

@enduml