@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor ":SalesManager" as AGVM
participant ":System" as SYSTEM

activate AGVM
AGVM -> SYSTEM : requests to see a questionnaire's statistical report
activate SYSTEM

SYSTEM --> AGVM : shows questionnaire's statistical report
deactivate SYSTEM
deactivate AGVM

@enduml