@startuml
skinparam classAttributeIconSize 0


class RegisterClientUI <<presentation>>
class RegisterClientController <<application>>
class Client <<domain>>
class ClientRepository <<repository>>
class ClientBuilder <<builder>>

class Client {
- ClientID
- Name
- VAT
- Email
- PhoneNumber
}

class ClientRepository{
+save(newClient)
}


class ClientBuilder {
+withVAT()
+withEmail()
+withPhoneNumber()
+named()
+withAddresses()
+withAddress()
+buildOrThrow()
+withBirthDate()
+withGender()
+build()
}





class RegisterClientController {
  +registerClient(firstNames, surnames, email, phoneNumber, vat, addresses, birthDate, gender)
}

class RegisterClientUI {
    #doShow()

}

RegisterClientUI --> RegisterClientController : theController
RegisterClientController --> Client : newClient
RegisterClientController --> ClientRepository : clientRepository



RegisterClientUI ..> Client : newClient

ClientBuilder --> Client : theClient
RegisterClientUI ..> ClientBuilder

@enduml