@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor ":WarehouseEmployee" as WHEmployee
participant ":ConfigureAvailableAGVUI" as UI
participant ":ConfigureAvailableAGVController" as controller
participant ":PersistenceContext" as persistence
participant ":AppSettings" as settings
participant ":RepositoryFactory" as factory
participant ":AvailableAGVRepository" as repository

activate WHEmployee

WHEmployee -> UI: configureAvailableAGV()

activate UI



deactivate UI

deactivate WHEmployee

@enduml